receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
          - http://*
          - https://*

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
