#!/usr/bin/env node

/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Configuration generation wrapper script
 * This script:
 * 1. Runs the generate_config.sh bash script to clone the schema and generate TypeScript types
 * 2. Post-processes the generated file by adding license headers
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const SCRIPT_DIR = __dirname;
const GENERATED_FILE_PATH = path.join(SCRIPT_DIR, '../../experimental/packages/opentelemetry-configuration/src/generated/opentelemetry_configuration.ts');

function addLicenseHeader(content) {
  const licenseHeader = `/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is auto-generated by quicktype from the OpenTelemetry Configuration Schema
// DO NOT EDIT MANUALLY - run npm run generate:config to regenerate

`;

  return licenseHeader + content;
}

function postProcess() {
  try {
    if (!fs.existsSync(GENERATED_FILE_PATH)) {
      console.log('Generated file not found, skipping post-processing');
      return;
    }

    let content = fs.readFileSync(GENERATED_FILE_PATH, 'utf8');

    // Add license header if not present
    if (!content.includes('Copyright The OpenTelemetry Authors')) {
      content = addLicenseHeader(content);
    }

    // Write back the processed content
    fs.writeFileSync(GENERATED_FILE_PATH, content);
    console.log('Post-processing completed successfully');
  } catch (error) {
    console.error('Error during post-processing:', error);
    process.exit(1);
  }
}

function main() {
  try {
    console.log('Running configuration generation script...');

    // Run the bash script
    const scriptPath = path.join(SCRIPT_DIR, 'generate_config.sh');
    execSync(`bash "${scriptPath}"`, { stdio: 'inherit', cwd: SCRIPT_DIR });

    // Post-process the generated file
    postProcess();

    console.log('Configuration generation completed successfully');
  } catch (error) {
    console.error('Error during configuration generation:', error.message);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { postProcess };
