codecov:
  notify:
    require_ci_to_pass: no
ignore:
  - "*.js"
  - "**/karma.*.js"
  - "**/.eslintrc.js"
  - "**/*.config.*"
  - "scripts/"
comment:
  layout: "header, changes, diff, files"
  behavior: default
coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: auto
        threshold: 1%
