receivers:
  otlp:
    {}
# keep it when upgrading to version 0.5+
#    protocols:
#      grpc:
#      http:
#        endpoint: localhost:55680

exporters:
  zipkin:
    url: "http://zipkin-all-in-one:9411/api/v2/spans"

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch, queued_retry]
