/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

const fs = require('fs');
const os = require('os');
const path = require('path');

const appRoot = process.cwd();

const packageJsonUrl = path.resolve(`${appRoot}/package.json`);
const pjson = require(packageJsonUrl);

const content = `/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

// this is autogenerated file, see scripts/version-update.js
export const VERSION = '${pjson.version}';
`;

const fileUrl = path.join(appRoot, "src", "version.ts")

fs.writeFileSync(fileUrl, content);
