/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import { getStringFromEnv } from '@opentelemetry/core';
import type { ConfigFactory } from './IConfigFactory';
import * as fs from 'fs';
import * as yaml from 'yaml';
import { envVariableSubstitution } from './utils';
import type {
  AttributeNameValue,
  ConfigurationModel,
  TextMapPropagator,
} from './generated/types';
// Pre-compiled ajv validator — eliminates runtime schema compilation on cold start.
// Generated by `npm run generate:config`; do not import ajv directly here.
import * as validateConfig from './generated/validator';

export class FileConfigFactory implements ConfigFactory {
  private _config: ConfigurationModel;

  constructor() {
    this._config = parseConfigFile();
  }

  getConfigModel(): ConfigurationModel {
    return this._config;
  }
}

export function parseConfigFile(): ConfigurationModel {
  const supportedFileVersionPattern = /^1\.0$/;
  const configFile = getStringFromEnv('OTEL_CONFIG_FILE') || '';
  const file = fs.readFileSync(configFile, 'utf8');

  // Apply env var substitution to all string values before schema parsing
  const rawParsed = yaml.parse(file) as Record<string, unknown>;
  const processed = substituteEnvVars(rawParsed) as Record<string, unknown>;

  const fileFormat = processed?.file_format;
  if (!fileFormat || !supportedFileVersionPattern.test(String(fileFormat))) {
    throw new Error(
      `${configFile}: Unsupported file_format: "${fileFormat}". Must match ${supportedFileVersionPattern}.`
    );
  }

  const valid = validateConfig(processed);
  if (!valid) {
    let detail: string;
    if (!validateConfig.errors) {
      detail = 'unknown error';
    } else if (validateConfig.errors.length === 1) {
      const err = validateConfig.errors[0];
      detail = `${err.instancePath} ${err.message}`;
    } else {
      const sep = '\n  ';
      detail =
        sep +
        validateConfig.errors
          .map(e => `${e.instancePath} ${e.message}`)
          .join(sep);
    }
    throw new Error(
      `Invalid OpenTelemetry config file: ${configFile}: ${detail}`
    );
  }

  const data = processed as unknown as ConfigurationModel;

  // Strip file_format from output — it's a meta-field, not a config value
  delete (data as Record<string, unknown>)['file_format'];

  return data;
}

/**
 * Merge attributes from `resource.attributes` and `resource.attributes_list`
 * (comma-separated key=value pairs) into an `AttributeNameValue[]` array.
 * Entries already in `resource.attributes` taking precedence.
 *
 * Note: The returned array might not be a copy, so it should not be mutated.
 */
export function mergeResourceAttributesConfig(
  attributes?: AttributeNameValue[],
  attributes_list?: string | null
): AttributeNameValue[] | undefined {
  if (!attributes_list) {
    return attributes;
  }

  const mergedAttrs = attributes ? attributes.slice() : [];
  const existingNames = new Set(mergedAttrs.map(a => a.name));

  // TODO(6769): handle percent-encoding, also apply attr limts if any in config?
  for (const pair of attributes_list.split(',')) {
    const eqIdx = pair.indexOf('=');
    if (eqIdx > 0) {
      const name = pair.slice(0, eqIdx).trim();
      const value = pair.slice(eqIdx + 1).trim();
      if (name && !existingNames.has(name)) {
        mergedAttrs.push({ name, value, type: 'string' });
      }
    }
  }

  return mergedAttrs;
}

/**
 * Merge propagator.composite_list (comma-separated propagator names) into
 * propagator.composite, with entries already in composite taking precedence.
 * Merge TextMapPropagator configs from `propagator.composite` and `propagator.composite_list`
 * (comma-separated names) into a `TextMapPropagator[]` array.
 * Entries already in `propagator.composite` taking precedence.
 *
 * Note: The returned array might not be a copy, so it should not be mutated.
 */
export function mergePropagatorCompositeConfig(
  composite?: TextMapPropagator[],
  composite_list?: string | null
): TextMapPropagator[] | undefined {
  if (!composite_list) {
    return composite;
  }

  const mergedComposite = composite ? composite.slice() : [];
  const existingNames = new Set(mergedComposite.map(c => Object.keys(c)[0]));

  for (const name of composite_list.split(',')) {
    const trimmed = name.trim();
    if (trimmed && !existingNames.has(trimmed)) {
      mergedComposite.push({ [trimmed]: null });
      existingNames.add(trimmed);
    }
  }

  return mergedComposite;
}

const ENV_VAR_PATTERN = /\$\{[^}]+\}/;

function substituteEnvVars(obj: unknown): unknown {
  if (typeof obj === 'string') {
    // Only coerce if the string contained env var substitution syntax,
    // so that plain YAML strings (e.g. quoted "1234") are not type-coerced.
    const hasSubstitution = ENV_VAR_PATTERN.test(obj);
    const substituted = envVariableSubstitution(obj);
    return hasSubstitution ? yamlCoerce(substituted) : substituted;
  }
  if (Array.isArray(obj)) {
    return obj.map(substituteEnvVars);
  }
  if (typeof obj === 'object' && obj !== null) {
    return Object.fromEntries(
      Object.entries(obj).map(([k, v]) => [k, substituteEnvVars(v)])
    );
  }
  return obj;
}

/**
 * Re-coerce a string value to its YAML-equivalent primitive type.
 * Env var substitution always returns strings; this converts them back
 * to booleans/numbers/null where the schema expects those types.
 */
function yamlCoerce(value: string): unknown {
  if (value === 'true') return true;
  if (value === 'false') return false;
  if (value === 'null' || value === '') return null;
  if (/^-?\d+$/.test(value)) return parseInt(value, 10);
  if (/^-?\d+\.\d+$/.test(value)) return parseFloat(value);
  return value;
}
