/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import { getStringFromEnv } from '@opentelemetry/core';
import type { ConfigFactory } from './IConfigFactory';
import * as fs from 'fs';
import * as yaml from 'yaml';
import { diag } from '@opentelemetry/api';
import { envVariableSubstitution } from './utils';
import { SeverityNumber } from './generated/types';
import type {
  BatchLogRecordProcessor,
  BatchSpanProcessor,
  CardinalityLimits,
  ConfigurationModel,
  PeriodicMetricReader,
} from './generated/types';
// Pre-compiled ajv validator — eliminates runtime schema compilation on cold start.
// Generated by `npm run generate:config`; do not import ajv directly here.
// eslint-disable-next-line @typescript-eslint/no-require-imports
import validateConfig = require('./generated/validator');

export class FileConfigFactory implements ConfigFactory {
  private _config: ConfigurationModel;

  constructor() {
    this._config = parseConfigFile();
  }

  getConfigModel(): ConfigurationModel {
    return this._config;
  }
}

export function hasValidConfigFile(): boolean {
  const configFile = getStringFromEnv('OTEL_CONFIG_FILE');
  if (configFile) {
    if (
      !(configFile.endsWith('.yaml') || configFile.endsWith('.yml')) ||
      !fs.existsSync(configFile)
    ) {
      diag.warn(
        `Config file ${configFile} set on OTEL_CONFIG_FILE is not valid`
      );
      return false;
    }
    return true;
  }
  return false;
}

export function parseConfigFile(): ConfigurationModel {
  const supportedFileVersionPattern = /^1\.0$/;
  const configFile = getStringFromEnv('OTEL_CONFIG_FILE') || '';
  const file = fs.readFileSync(configFile, 'utf8');

  // Apply env var substitution to all string values before schema parsing
  const rawParsed = yaml.parse(file) as Record<string, unknown>;
  const substituted = substituteEnvVars(rawParsed) as Record<string, unknown>;

  const fileFormat = substituted?.file_format;
  if (!fileFormat || !supportedFileVersionPattern.test(String(fileFormat))) {
    throw new Error(
      `Unsupported file_format: "${fileFormat}". Must match ${supportedFileVersionPattern}.`
    );
  }

  // Preprocess: convert null to [] for provider processors/readers so schema
  // validation passes, then warn application-level after parse
  const preprocessed = preprocessNullArrays(substituted) as Record<
    string,
    unknown
  >;

  // Normalize YAML null type-tag values to {} before validation
  normalizeYamlNulls(preprocessed);

  const valid = validateConfig(preprocessed);
  if (!valid) {
    const firstError = validateConfig.errors?.[0];
    const detail = firstError
      ? `${firstError.instancePath} ${firstError.message}`
      : 'unknown error';
    throw new Error(`Invalid OpenTelemetry config file: ${detail.trim()}`);
  }

  const data = preprocessed as unknown as ConfigurationModel;

  // Strip file_format from output — it's a meta-field, not a config value
  delete (data as Record<string, unknown>)['file_format'];

  applyConfigDefaults(data);
  mergeAttributesList(data);
  mergeCompositeList(data);
  applyBatchProcessorDefaults(data);
  applyPeriodicReaderDefaults(data);
  applyOtlpHttpEncodingDefaults(data);

  // Warn for providers with empty processors/readers
  if (data.tracer_provider?.processors?.length === 0) {
    diag.warn('TracerProvider must have at least one processor configured');
  }
  if (data.meter_provider?.readers?.length === 0) {
    diag.warn('MeterProvider must have at least one reader configured');
  }
  if (data.logger_provider?.processors?.length === 0) {
    diag.warn('LoggerProvider must have at least one processor configured');
  }

  return data;
}

/**
 * Apply default encoding ('protobuf') to all otlp_http exporters in the config
 * where encoding was not explicitly specified. The spec defines protobuf as the
 * default encoding for OTLP HTTP exporters.
 */
function applyOtlpHttpEncodingDefaults(data: ConfigurationModel): void {
  const applyEncoding = (
    exporter: { encoding?: string | null } | null | undefined
  ) => {
    if (exporter && exporter.encoding == null) {
      exporter.encoding = 'protobuf';
    }
  };

  for (const processor of data.tracer_provider?.processors ?? []) {
    applyEncoding(processor.batch?.exporter?.otlp_http);
    applyEncoding(processor.simple?.exporter?.otlp_http);
  }

  for (const reader of data.meter_provider?.readers ?? []) {
    applyEncoding(reader.periodic?.exporter?.otlp_http);
  }

  for (const processor of data.logger_provider?.processors ?? []) {
    applyEncoding(processor.batch?.exporter?.otlp_http);
    applyEncoding(processor.simple?.exporter?.otlp_http);
  }
}

/**
 * Merge resource.attributes_list (comma-separated key=value pairs) into
 * resource.attributes, with entries already in attributes taking precedence.
 */
function mergeAttributesList(data: ConfigurationModel): void {
  const resource = data.resource;
  const list = resource?.attributes_list;
  if (typeof list !== 'string' || !list.trim()) return;

  if (resource!.attributes == null) {
    resource!.attributes = [];
  }

  const existingKeys = new Set(
    resource!.attributes.map((a: { name: string }) => a.name)
  );

  for (const pair of list.split(',')) {
    const eqIdx = pair.indexOf('=');
    if (eqIdx > 0) {
      const key = pair.slice(0, eqIdx).trim();
      const value = pair.slice(eqIdx + 1).trim();
      if (key && !existingKeys.has(key)) {
        resource!.attributes.push({ name: key, value, type: 'string' });
      }
    }
  }
}

/**
 * Merge propagator.composite_list (comma-separated propagator names) into
 * propagator.composite, with entries already in composite taking precedence.
 */
function mergeCompositeList(data: ConfigurationModel): void {
  const propagator = data.propagator;
  const list = propagator?.composite_list;
  if (typeof list !== 'string' || !list.trim()) return;

  if (propagator!.composite == null) {
    propagator!.composite = [];
  }

  const existingNames = new Set(
    (propagator!.composite as Array<Record<string, unknown>>).map(
      entry => Object.keys(entry)[0]
    )
  );

  for (const name of list.split(',')) {
    const trimmed = name.trim();
    if (trimmed && !existingNames.has(trimmed)) {
      (propagator!.composite as Array<Record<string, unknown>>).push({
        [trimmed]: {},
      });
    }
  }
}

/**
 * Apply spec-defined defaults for batch span/log-record processor fields that
 * are not encoded in the JSON schema.
 */
function applyBatchProcessorDefaults(data: ConfigurationModel): void {
  const applyDefaults = (
    batch: BatchSpanProcessor | BatchLogRecordProcessor
  ) => {
    if (batch.schedule_delay == null) batch.schedule_delay = 5000;
    if (batch.export_timeout == null) batch.export_timeout = 30000;
    if (batch.max_queue_size == null) batch.max_queue_size = 2048;
    if (batch.max_export_batch_size == null) batch.max_export_batch_size = 512;
  };

  for (const processor of data.tracer_provider?.processors ?? []) {
    if (processor.batch) applyDefaults(processor.batch);
  }
  for (const processor of data.logger_provider?.processors ?? []) {
    if (processor.batch) applyDefaults(processor.batch);
  }
}

/**
 * Apply spec-defined defaults for periodic metric reader fields.
 */
function applyPeriodicReaderDefaults(data: ConfigurationModel): void {
  for (const reader of data.meter_provider?.readers ?? []) {
    const periodic = reader.periodic as PeriodicMetricReader | undefined;
    if (!periodic) continue;
    if (periodic.interval == null) periodic.interval = 60000;
    if (periodic.timeout == null) periodic.timeout = 30000;
    if (periodic.cardinality_limits == null) {
      periodic.cardinality_limits = { default: 2000 } as CardinalityLimits;
    }
  }
}

/**
 * Apply spec-defined defaults that are not encoded in the JSON schema.
 * Both FileConfigFactory and EnvironmentConfigFactory apply the same defaults
 * so consumers see consistent behaviour regardless of config source.
 */
function applyConfigDefaults(data: ConfigurationModel): void {
  if (data.disabled == null) {
    data.disabled = false;
  }
  if (data.log_level == null) {
    data.log_level = SeverityNumber.Info;
  }
  if (data.attribute_limits == null) {
    data.attribute_limits = { attribute_count_limit: 128 };
  } else if (data.attribute_limits.attribute_count_limit == null) {
    data.attribute_limits.attribute_count_limit = 128;
  }
}

/**
 * Object type-tag keys that may appear as nested (non-array-element) properties.
 * YAML `console:` (no value) parses to `{ console: null }`, but the SDK checks
 * `if (exporter.console)` — truthy — so null must become {}.
 *
 * We exclude keys that are also used as nullable primitives in other contexts
 * (e.g. `host` is a string field in prometheus config; detectors use it as a
 * type-tag but only as array elements, which are already handled below).
 */
const NESTED_OBJECT_TYPE_TAGS = new Set([
  // Exporter type discriminators (nested inside simple/batch processor)
  'console',
  // Sampler type discriminators (nested inside tracer_provider.sampler)
  'always_on',
  'always_off',
  'trace_id_ratio_based',
  'parent_based',
  'jaeger_remote',
  // Propagator type discriminators (array elements, but covered here for completeness)
  'tracecontext',
  'baggage',
  'b3',
  'b3multi',
  'xray',
  // Telemetry producer type discriminators
  'opencensus',
]);

/**
 * Normalizes YAML null values to empty objects for discriminated-union type-tag fields.
 *
 * YAML `key:` (no value) parses to `{ key: null }`, but the SDK checks `if (obj.key)`
 * to determine which type to instantiate — null fails that check. Two cases:
 *
 * 1. Array element properties: convert ALL null-valued keys to {} (handles detectors,
 *    composite propagators, and most exporter/processor discriminators).
 * 2. Nested NESTED_OBJECT_TYPE_TAGS: convert known type-discriminator keys to {} when
 *    encountered anywhere in the tree (handles sampler types, console exporter nested
 *    inside simple/batch, etc.).
 *
 * Top-level nullable primitive fields (disabled, log_level, endpoint, ca_file, etc.)
 * are NOT in NESTED_OBJECT_TYPE_TAGS and are left as-is; applyConfigDefaults()
 * handles the boolean/string ones that need defaults.
 */
function normalizeYamlNulls(value: unknown): void {
  if (value == null || typeof value !== 'object') return;
  if (Array.isArray(value)) {
    for (const item of value) {
      if (item != null && typeof item === 'object' && !Array.isArray(item)) {
        // All null-valued properties of array elements are type-tag discriminators.
        for (const key of Object.keys(item as object)) {
          if ((item as Record<string, unknown>)[key] === null) {
            (item as Record<string, unknown>)[key] = {};
          }
        }
      }
      normalizeYamlNulls(item);
    }
  } else {
    for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
      if (val === null && NESTED_OBJECT_TYPE_TAGS.has(key)) {
        (value as Record<string, unknown>)[key] = {};
      } else {
        normalizeYamlNulls(val);
      }
    }
  }
}

function preprocessNullArrays(obj: unknown): unknown {
  if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) return obj;
  const record = obj as Record<string, unknown>;
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(record)) {
    if ((k === 'processors' || k === 'readers') && v === null) {
      result[k] = [];
    } else {
      result[k] = preprocessNullArrays(v);
    }
  }
  return result;
}

const ENV_VAR_PATTERN = /\$\{[^}]+\}/;

function substituteEnvVars(obj: unknown): unknown {
  if (typeof obj === 'string') {
    // Only coerce if the string contained env var substitution syntax,
    // so that plain YAML strings (e.g. quoted "1234") are not type-coerced.
    const hasSubstitution = ENV_VAR_PATTERN.test(obj);
    const substituted = envVariableSubstitution(obj) ?? obj;
    return hasSubstitution ? yamlCoerce(substituted) : substituted;
  }
  if (Array.isArray(obj)) {
    return obj.map(substituteEnvVars);
  }
  if (typeof obj === 'object' && obj !== null) {
    return Object.fromEntries(
      Object.entries(obj).map(([k, v]) => [k, substituteEnvVars(v)])
    );
  }
  return obj;
}

/**
 * Re-coerce a string value to its YAML-equivalent primitive type.
 * Env var substitution always returns strings; this converts them back
 * to booleans/numbers/null where the schema expects those types.
 */
function yamlCoerce(value: string): unknown {
  if (value === 'true') return true;
  if (value === 'false') return false;
  if (value === 'null' || value === '') return null;
  if (/^-?\d+$/.test(value)) return parseInt(value, 10);
  if (/^-?\d+\.\d+$/.test(value)) return parseFloat(value);
  return value;
}
