// source: opentelemetry/proto/collector/trace/v1/trace_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var opentelemetry_proto_trace_v1_trace_pb = require('../../../../../opentelemetry/proto/trace/v1/trace_pb.js');
goog.object.extend(proto, opentelemetry_proto_trace_v1_trace_pb);
goog.exportSymbol('proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest', null, global);
goog.exportSymbol('proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.repeatedFields_, null);
};
goog.inherits(proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.displayName = 'proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.displayName = 'proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceSpansList: jspb.Message.toObjectList(msg.getResourceSpansList(),
    opentelemetry_proto_trace_v1_trace_pb.ResourceSpans.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest;
  return proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new opentelemetry_proto_trace_v1_trace_pb.ResourceSpans;
      reader.readMessage(value,opentelemetry_proto_trace_v1_trace_pb.ResourceSpans.deserializeBinaryFromReader);
      msg.addResourceSpans(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceSpansList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      opentelemetry_proto_trace_v1_trace_pb.ResourceSpans.serializeBinaryToWriter
    );
  }
};


/**
 * repeated opentelemetry.proto.trace.v1.ResourceSpans resource_spans = 1;
 * @return {!Array<!proto.opentelemetry.proto.trace.v1.ResourceSpans>}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.prototype.getResourceSpansList = function() {
  return /** @type{!Array<!proto.opentelemetry.proto.trace.v1.ResourceSpans>} */ (
    jspb.Message.getRepeatedWrapperField(this, opentelemetry_proto_trace_v1_trace_pb.ResourceSpans, 1));
};


/**
 * @param {!Array<!proto.opentelemetry.proto.trace.v1.ResourceSpans>} value
 * @return {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} returns this
*/
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.prototype.setResourceSpansList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.opentelemetry.proto.trace.v1.ResourceSpans=} opt_value
 * @param {number=} opt_index
 * @return {!proto.opentelemetry.proto.trace.v1.ResourceSpans}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.prototype.addResourceSpans = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.opentelemetry.proto.trace.v1.ResourceSpans, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} returns this
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.prototype.clearResourceSpansList = function() {
  return this.setResourceSpansList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse;
  return proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.opentelemetry.proto.collector.trace.v1);
