/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.15.6
 * source: opentelemetry/proto/collector/metrics/v1/metrics_service.proto
 * git: https://github.com/thesayyn/protoc-gen-ts
 *  */
import * as dependency_1 from "./../../../metrics/v1/metrics";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace opentelemetry.proto.collector.metrics.v1 {
    export class ExportMetricsServiceRequest extends pb_1.Message {
        constructor(data?: any[] | {
            resource_metrics?: dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("resource_metrics" in data && data.resource_metrics != undefined) {
                    this.resource_metrics = data.resource_metrics;
                }
            }
        }
        get resource_metrics() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics, 1) as dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics[];
        }
        set resource_metrics(value: dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            resource_metrics?: ReturnType<typeof dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics.prototype.toObject>[];
        }) {
            const message = new ExportMetricsServiceRequest({});
            if (data.resource_metrics != null) {
                message.resource_metrics = data.resource_metrics.map(item => dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                resource_metrics?: ReturnType<typeof dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics.prototype.toObject>[];
            } = {};
            if (this.resource_metrics != null) {
                data.resource_metrics = this.resource_metrics.map((item: dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.resource_metrics !== undefined)
                writer.writeRepeatedMessage(1, this.resource_metrics, (item: dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ExportMetricsServiceRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ExportMetricsServiceRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.resource_metrics, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics.deserialize(reader), dependency_1.opentelemetry.proto.metrics.v1.ResourceMetrics));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ExportMetricsServiceRequest {
            return ExportMetricsServiceRequest.deserialize(bytes);
        }
    }
    export class ExportMetricsServiceResponse extends pb_1.Message {
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}) {
            const message = new ExportMetricsServiceResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ExportMetricsServiceResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ExportMetricsServiceResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ExportMetricsServiceResponse {
            return ExportMetricsServiceResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedMetricsServiceService {
        static definition = {
            Export: {
                path: "/opentelemetry.proto.collector.metrics.v1.MetricsService/Export",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ExportMetricsServiceRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ExportMetricsServiceRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: ExportMetricsServiceResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => ExportMetricsServiceResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract Export(call: grpc_1.ServerUnaryCall<ExportMetricsServiceRequest, ExportMetricsServiceResponse>, callback: grpc_1.sendUnaryData<ExportMetricsServiceResponse>): void;
    }
    export class MetricsServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedMetricsServiceService.definition, "MetricsService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options)
        }
        Export: GrpcUnaryServiceInterface<ExportMetricsServiceRequest, ExportMetricsServiceResponse> = (message: ExportMetricsServiceRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<ExportMetricsServiceResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<ExportMetricsServiceResponse>, callback?: grpc_1.requestCallback<ExportMetricsServiceResponse>): grpc_1.ClientUnaryCall => {
            return super.Export(message, metadata, options, callback);
        };
    }
}
