global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusProto
    - PrometheusText0.0.4
    - PrometheusText1.0.0

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
