name: Benchmark Tests

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  benchmark-tests:
    permissions:
      contents: write # required for pushing benchmark results to gh-pages
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - ^26.3.0
    runs-on: oracle-bare-metal-64cpu-1024gb-x86-64-ubuntu-24
    container:
      image: ubuntu:26.04@sha256:678c6550cc43645e08669028bc177f50be4e7c5b8cca677067b1914d4afc7a03
    timeout-minutes: 10
    steps:
      # Apt packages:
      # - git: Needed for 'npm run submodule'
      # - libatomic1: Needed by Node.js 26
      - name: Setup container environment
        run: |
          apt-get update && apt-get install --fix-missing -y git libatomic1

      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      # Avoid "detected dubious ownership in repository" error when running
      # `npm run submodule`.
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: ${{ matrix.node_version }}

      - name: Bootstrap
        run: npm ci --ignore-scripts

      - name: Build 🔧
        run: npm run compile

      - name: Benchmark tests
        run: |
          npm run test:bench
          find . -name .benchmark-results.txt -exec cat {} + > combined_benchmarks.txt

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1.22.1
        with:
          tool: 'benchmarkjs'
          output-file-path: combined_benchmarks.txt
          gh-pages-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "benchmarks"
          auto-push: true
