name: Create or Update Release PR

on:
  workflow_dispatch:
    inputs:
      stable_sdk_release:
        type: choice
        description: 'Stable SDK packages (./packages/*)'
        default: 'inherit'
        options:
          - inherit # no release unless required by other settings
          - patch
          - minor
      experimental_release:
        type: choice
        description: 'Experimental packages (./experimental/packages/*)'
        default: 'inherit'
        options:
          - inherit # matches stable SDK if released, otherwise no release
          - patch
          - minor
      api_release:
        type: choice
        description: 'API package (./api) - makes stable SDK and experimental inherit the bump'
        default: 'inherit'
        options:
          - inherit # no release
          - patch
          - minor
      semconv_release:
        type: choice
        description: 'Semantic Conventions package (./semantic-conventions)'
        default: 'inherit'
        options:
          - inherit # no release
          - patch
          - minor

permissions:
  contents: read

jobs:
  create-or-update-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: otelbot-token
        with:
          client-id: ${{ vars.OTELBOT_JS_CLIENT_ID }}
          private-key: ${{ secrets.OTELBOT_JS_PRIVATE_KEY }}
          # Scope to just the permissions required by the "Create/Update Release PR" step below.
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.otelbot-token.outputs.token }}
          # Credentials are used in 'Create/Update Release PR' git commands below.
          persist-credentials: true

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version: ^26.3.0
      - run: npm ci --ignore-scripts

      - name: Create/Update Release PR
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com
          npm run github:create_or_update_release_pr
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
          STABLE_SDK_RELEASE: ${{ github.event.inputs.stable_sdk_release }}
          EXPERIMENTAL_RELEASE: ${{ github.event.inputs.experimental_release }}
          API_RELEASE: ${{ github.event.inputs.api_release }}
          SEMCONV_RELEASE: ${{ github.event.inputs.semconv_release }}
          RELEASE_PR_REMOTE: origin
