name: Documentation tests

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: ^26.3.0

      - name: Bootstrap
        run: npm ci --ignore-scripts

      - name: Build documentation
        run: |
          npm run compile
          NODE_OPTIONS=--max-old-space-size=6144 npm run docs

      - name: Check documentation links
        run: npm run docs:test
