name: Deploy API Documentation

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-deploy:
    permissions:
      contents: write # required for deploying documentation to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ^26.3.0
          # Disable caching in release workflows (https://docs.zizmor.sh/audits/#cache-poisoning).
          package-manager-cache: false

      - name: Install and Build 🔧
        run: |
          npm ci --ignore-scripts
          npm run compile

      - name: Build Docs
        run: npm run docs
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Deploy Documentation 🚀
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          # ensure we don't override benchmark data
          clean-exclude: |
            benchmarks/**
