name: Markdown Linter

# Link checking costs tens of minutes to run.
# Runs everyday at 9 am.
on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      # checks all markdown including all subfolders
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown-lint.config.json'
