name: NPM Permission Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-permission:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: '@opentelemetry'

      - name: whoami
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

