name: Publish instrumentation

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch, tag, or SHA to publish from
        required: true
        default: coralogix-autoinstrumentation

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install --workspaces=false --include=dev
          ./node_modules/.bin/tsc -p tsconfig.json
          ./node_modules/.bin/tsc -p tsconfig.esm.json
          ./node_modules/.bin/tsc -p tsconfig.esnext.json
          npm pkg set name=@coralogix/instrumentation
          npm publish --ignore-scripts --access public
        working-directory: ./experimental/packages/opentelemetry-instrumentation
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
