name: SBOM
on:
  release:
    types: [published]

permissions: read-all

jobs:
  generate-sboms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "22.22.1" # pin to avoid bug in 22.22.2

      - run: npm install -g npm@latest

      - name: Bootstrap
        run: npm ci --ignore-scripts

      - name: Generate SBOM for core packages
        if: ${{ ! startsWith(github.ref, 'refs/tags/experimental') && ! startsWith(github.ref, 'refs/tags/api') }}
        run: |
          for dir in $(find packages -mindepth 1 -maxdepth 1 -type d)
          do
            dir_name=$(basename "$dir")
            echo "Generating SBOM for $dir_name"
            npm sbom --sbom-format=spdx --legacy-peer-deps --workspace ${dir} > "opentelemetry-js_${dir_name}.spdx.json"
          done

      - name: Generate SBOM for the API package
        if: startsWith(github.ref, 'refs/tags/api/')
        run: |
          npm sbom --sbom-format=spdx --legacy-peer-deps --workspace api > opentelemetry-js_api.spdx.json

      - name: Generate SBOMs for experimental packages
        if: startsWith(github.ref, 'refs/tags/experimental/')
        run: |
          for dir in $(find experimental/packages -mindepth 1 -maxdepth 1 -type d)
          do
            dir_name=$(basename "$dir")
            echo "Generating SBOM for $dir_name"
            npm sbom --sbom-format=spdx --legacy-peer-deps --workspace ${dir} > "opentelemetry-js_${dir_name}.spdx.json"
          done

      - name: Zip all SBOM files
        run: |
          zip sbom.zip *.spdx.json

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          archive: false
          path: ./sbom.zip

  add-release-artifact:
    needs: generate-sboms
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact from generate-sboms
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: sbom.zip
          skip-decompress: true
      - name: Upload release asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          mv sbom.zip SBOM.zip
          gh release upload "$TAG" ./SBOM.zip --clobber
