name: W3C Trace Context Integration Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
          node-version: 22

      - name: Install and Bootstrap 🔧
        run: npm ci --ignore-scripts

      - name: Build 🔧
        run: npm run compile

      - name: Run W3C Test harness
        run: ./integration-tests/tracecontext-integration-test.sh
